# Generated by Django 4.2.4 on 2023-08-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='alt',
            field=models.TextField(null=True, verbose_name='alt'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='media_image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='title',
            field=models.TextField(null=True, verbose_name='title'),
        ),
    ]
