# Generated by Django 4.2.4 on 2023-08-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0002_imagemodel_alt_imagemodel_media_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('href', models.TextField(verbose_name='Ссылка')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customize.displaymodel')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
