# Generated by Django 4.2.4 on 2023-08-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0003_linkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='title'),
        ),
    ]
