# Generated by Django 4.2.4 on 2023-08-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0004_linkmodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('visible', models.BooleanField(blank=True, null=True, verbose_name='Скрывать')),
                ('text', models.TextField(verbose_name='Текст')),
                ('href', models.TextField(verbose_name='Ссылка')),
                ('title', models.TextField(blank=True, null=True, verbose_name='title')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customize.displaymodel')),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
            },
        ),
    ]
