# Generated by Django 4.2.4 on 2023-08-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0005_buttonmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(verbose_name='Показать')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок карточки')),
                ('subtitle', models.CharField(max_length=64, verbose_name='Подзаголовок карточки')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('descr', models.TextField(verbose_name='Характеристики товара')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.AlterField(
            model_name='buttonmodel',
            name='visible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Показывать'),
        ),
    ]
