# Generated by Django 4.2.4 on 2023-08-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0006_cardmodel_alter_buttonmodel_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='href',
            field=models.TextField(default='', verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
