# Generated by Django 4.2.4 on 2023-08-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0009_formmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название иконки')),
                ('href', models.TextField(verbose_name='Ссылка')),
                ('icon', models.CharField(max_length=64, verbose_name='Название иконки из font-awesome')),
            ],
            options={
                'verbose_name': 'Иконка',
                'verbose_name_plural': 'Иконки',
            },
        ),
    ]
