# Generated by Django 4.2.4 on 2023-09-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0010_iconmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='price',
            field=models.CharField(max_length=64, verbose_name='Цена'),
        ),
    ]
