# Generated by Django 4.2.4 on 2023-09-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0012_buttonmodel_add_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonmodel',
            name='add_form',
            field=models.BooleanField(default=False, verbose_name='Форма номер 2'),
            preserve_default=False,
        ),
    ]
