# Generated by Django 4.2.4 on 2023-09-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0016_pagemodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='href',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
